events {}

http {
  upstream app_upstream {
    server app:8000;
  }

  server {
    listen 80;
    server_name _;

    location / {
      proxy_pass http://app_upstream;
    }
  }

  server {
    listen 443;
    server_name _;

    location / {
      proxy_pass http://app_upstream;
    }
  }
}


